export interface Currency {
  code: string;
  symbol: string;
  name: string;
  flag: string;
}

export const currencies: Currency[] = [
  { code: 'XOF', symbol: 'FCFA', name: 'Franc CFA (BCEAO)', flag: '🇸🇳' },
  { code: 'XAF', symbol: 'FCFA', name: 'Franc CFA (BEAC)', flag: '🇨🇲' },
  { code: 'EUR', symbol: '€', name: 'Euro', flag: '🇪🇺' },
  { code: 'USD', symbol: '$', name: 'Dollar américain', flag: '🇺🇸' },
  { code: 'GBP', symbol: '£', name: 'Livre sterling', flag: '🇬🇧' },
  { code: 'JPY', symbol: '¥', name: 'Yen japonais', flag: '🇯🇵' },
  { code: 'CNY', symbol: '¥', name: 'Yuan chinois', flag: '🇨🇳' },
  { code: 'MXN', symbol: '$', name: 'Peso mexicain', flag: '🇲🇽' },
  { code: 'ARS', symbol: '$', name: 'Peso argentin', flag: '🇦🇷' },
  { code: 'COP', symbol: '$', name: 'Peso colombien', flag: '🇨🇴' },
  { code: 'ZAR', symbol: 'R', name: 'Rand sud-africain', flag: '🇿🇦' },
  { code: 'NGN', symbol: '₦', name: 'Naira nigérian', flag: '🇳🇬' },
  { code: 'GHS', symbol: '₵', name: 'Cedi ghanéen', flag: '🇬🇭' },
  { code: 'KES', symbol: 'KSh', name: 'Shilling kényan', flag: '🇰🇪' },
  { code: 'MAD', symbol: 'DH', name: 'Dirham marocain', flag: '🇲🇦' },
  { code: 'EGP', symbol: 'E£', name: 'Livre égyptienne', flag: '🇪🇬' },
  { code: 'TND', symbol: 'DT', name: 'Dinar tunisien', flag: '🇹🇳' },
  { code: 'DZD', symbol: 'DA', name: 'Dinar algérien', flag: '🇩🇿' },
  { code: 'INR', symbol: '₹', name: 'Roupie indienne', flag: '🇮🇳' },
  { code: 'BRL', symbol: 'R$', name: 'Real brésilien', flag: '🇧🇷' },
  { code: 'CAD', symbol: 'C$', name: 'Dollar canadien', flag: '🇨🇦' },
  { code: 'AUD', symbol: 'A$', name: 'Dollar australien', flag: '🇦🇺' },
  { code: 'CHF', symbol: 'CHF', name: 'Franc suisse', flag: '🇨🇭' },
  { code: 'RUB', symbol: '₽', name: 'Rouble russe', flag: '🇷🇺' },
  { code: 'KRW', symbol: '₩', name: 'Won sud-coréen', flag: '🇰🇷' },
  { code: 'SGD', symbol: 'S$', name: 'Dollar singapourien', flag: '🇸🇬' },
  { code: 'HKD', symbol: 'HK$', name: 'Dollar de Hong Kong', flag: '🇭🇰' },
  { code: 'SEK', symbol: 'kr', name: 'Couronne suédoise', flag: '🇸🇪' },
  { code: 'NOK', symbol: 'kr', name: 'Couronne norvégienne', flag: '🇳🇴' },
  { code: 'DKK', symbol: 'kr', name: 'Couronne danoise', flag: '🇩🇰' },
  { code: 'PLN', symbol: 'zł', name: 'Zloty polonais', flag: '🇵🇱' },
  { code: 'TRY', symbol: '₺', name: 'Livre turque', flag: '🇹🇷' },
  { code: 'THB', symbol: '฿', name: 'Baht thaïlandais', flag: '🇹🇭' },
  { code: 'IDR', symbol: 'Rp', name: 'Roupie indonésienne', flag: '🇮🇩' },
  { code: 'MYR', symbol: 'RM', name: 'Ringgit malaisien', flag: '🇲🇾' },
  { code: 'PHP', symbol: '₱', name: 'Peso philippin', flag: '🇵🇭' },
  { code: 'VND', symbol: '₫', name: 'Dong vietnamien', flag: '🇻🇳' },
  { code: 'AED', symbol: 'AED', name: 'Dirham des EAU', flag: '🇦🇪' },
  { code: 'SAR', symbol: 'SR', name: 'Riyal saoudien', flag: '🇸🇦' },
  { code: 'ILS', symbol: '₪', name: 'Shekel israélien', flag: '🇮🇱' },
  { code: 'CLP', symbol: '$', name: 'Peso chilien', flag: '🇨🇱' },
  { code: 'PEN', symbol: 'S/', name: 'Sol péruvien', flag: '🇵🇪' },
  { code: 'UYU', symbol: '$', name: 'Peso uruguayen', flag: '🇺🇾' },
  { code: 'CRC', symbol: '₡', name: 'Colon costaricain', flag: '🇨🇷' },
  { code: 'GTQ', symbol: 'Q', name: 'Quetzal guatémaltèque', flag: '🇬🇹' },
  { code: 'HNL', symbol: 'L', name: 'Lempira hondurien', flag: '🇭🇳' },
  { code: 'NIO', symbol: 'C$', name: 'Córdoba nicaraguayen', flag: '🇳🇮' },
  { code: 'PAB', symbol: 'B/', name: 'Balboa panaméen', flag: '🇵🇦' },
  { code: 'DOP', symbol: 'RD$', name: 'Peso dominicain', flag: '🇩🇴' },
  { code: 'JMD', symbol: 'J$', name: 'Dollar jamaïcain', flag: '🇯🇲' },
  { code: 'HTG', symbol: 'G', name: 'Gourde haïtienne', flag: '🇭🇹' },
  { code: 'CUP', symbol: '₱', name: 'Peso cubain', flag: '🇨🇺' },
  { code: 'BSD', symbol: 'B$', name: 'Dollar bahaméen', flag: '🇧🇸' },
  { code: 'TTD', symbol: 'TT$', name: 'Dollar de Trinité-et-Tobago', flag: '🇹🇹' },
  { code: 'BBD', symbol: 'Bds$', name: 'Dollar barbadien', flag: '🇧🇧' },
  { code: 'XCD', symbol: 'EC$', name: 'Dollar des Caraïbes orientales', flag: '🇦🇬' },
  { code: 'GNF', symbol: 'FG', name: 'Franc guinéen', flag: '🇬🇳' },
  { code: 'MGA', symbol: 'Ar', name: 'Ariary malgache', flag: '🇲🇬' },
  { code: 'MUR', symbol: '₨', name: 'Roupie mauricienne', flag: '🇲🇺' },
  { code: 'SCR', symbol: '₨', name: 'Roupie seychelloise', flag: '🇸🇨' },
  { code: 'TZS', symbol: 'TSh', name: 'Shilling tanzanien', flag: '🇹🇿' },
  { code: 'UGX', symbol: 'USh', name: 'Shilling ougandais', flag: '🇺🇬' },
  { code: 'RWF', symbol: 'FRw', name: 'Franc rwandais', flag: '🇷🇼' },
  { code: 'ETB', symbol: 'Br', name: 'Birr éthiopien', flag: '🇪🇹' },
  { code: 'BWP', symbol: 'P', name: 'Pula botswanais', flag: '🇧🇼' },
  { code: 'NAD', symbol: 'N$', name: 'Dollar namibien', flag: '🇳🇦' },
  { code: 'MZN', symbol: 'MT', name: 'Metical mozambicain', flag: '🇲🇿' },
  { code: 'ZMW', symbol: 'ZK', name: 'Kwacha zambien', flag: '🇿🇲' },
  { code: 'AOA', symbol: 'Kz', name: 'Kwanza angolais', flag: '🇦🇴' },
  { code: 'CVE', symbol: '$', name: 'Escudo cap-verdien', flag: '🇨🇻' },
  { code: 'GMD', symbol: 'D', name: 'Dalasi gambien', flag: '🇬🇲' },
  { code: 'LRD', symbol: 'L$', name: 'Dollar libérien', flag: '🇱🇷' },
  { code: 'SLL', symbol: 'Le', name: 'Leone sierra-léonais', flag: '🇸🇱' },
  { code: 'SDG', symbol: 'ج.س', name: 'Livre soudanaise', flag: '🇸🇩' },
  { code: 'SSP', symbol: '£', name: 'Livre sud-soudanaise', flag: '🇸🇸' },
  { code: 'SOS', symbol: 'Sh', name: 'Shilling somalien', flag: '🇸🇴' },
  { code: 'DJF', symbol: 'Fdj', name: 'Franc djiboutien', flag: '🇩🇯' },
  { code: 'ERN', symbol: 'Nfk', name: 'Nakfa érythréen', flag: '🇪🇷' },
  { code: 'BIF', symbol: 'FBu', name: 'Franc burundais', flag: '🇧🇮' },
  { code: 'CDF', symbol: 'FC', name: 'Franc congolais', flag: '🇨🇩' },
  { code: 'STN', symbol: 'Db', name: 'Dobra santoméen', flag: '🇸🇹' },
  { code: 'KMF', symbol: 'CF', name: 'Franc comorien', flag: '🇰🇲' },
  { code: 'MWK', symbol: 'MK', name: 'Kwacha malawite', flag: '🇲🇼' },
  { code: 'SZL', symbol: 'E', name: 'Lilangeni eswatinien', flag: '🇸🇿' },
  { code: 'LSL', symbol: 'L', name: 'Loti lesothan', flag: '🇱🇸' },
];
